/**
 * This is a simple script that will remove exports
 * from the dist js file. So it would be compatible with
 * Google Apps Script
 */
const fs = require('fs').promises;

const main = async () => {
  const source = 'dist/biyete.gs.modern.js';
  const file = await fs.open(source, 'r');
  const contents = (await file.readFile()).toString();

  file.close();

  const out = 'dist/biyete.gs';
  const fileout = await fs.open(out, 'w');

  const sheetURL =
    "const sheetURL = 'https://docs.google.com/spreadsheets/d/<spreadsheet id>/edit#gid=0';";

  // standarize formatting
  // with the sheetURL at the beginning
  let content = contents
    .replace(sheetURL, '')
    .replace(
      "// Try to include #grid=0 at the end, to specify the spreadsheet's initial sheet.",
      ''
    )
    .replace('export default main;', '');

  content = `
// Configure URL to Google Sheets
// Try to include #grid=0 at the end, to specify the spreadsheet's initial sheet.
${sheetURL}

// AutoGenerated. Should not touch.
${content}
  `.trim();

  await fileout.writeFile(content);

  fileout.close();
};

main().catch((error) => {
  console.error(error);
});
