name: docker-ci
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master, production]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint and Test

        run: make github
